version: "3.8"

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1234:80"
    restart: always
    volumes:
      - ./app:/var/www/html

  database:
    image: mariadb
    restart: always
    environment:
      MARIADB_DATABASE: blog
      MARIADB_ROOT_PASSWORD: password
    volumes:
      - ./migration/dump.sql:/docker-entrypoint-initdb.d/dump.sql
      #- db_data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - "1616:8080"

#volumes:
#  db_data:


